spring:
  # 默认环境dev
  profiles:
    active: dev
  application:
    name: yupao-backend
  # datasource配置
  datasource:
    url: jdbc:mysql://localhost:3306/lkc
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lkc
  session:
    # session 失效时间（分钟）
    timeout: 86400
    # 表示从 redis 读写 session
    store-type: redis
  # Spring Boot 2.7.X使用PathPatternMatcher匹配路径，Swagger引用的Springfox使用的路径匹配是基于AntPathMatcher的，所以需要进行配置
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis配置
  redis:
    port: 6379
    host: localhost
    database: 1 #改使用第几个数据库
# 设置访问端口和路径
server:
  port: 8080
  servlet:
    context-path: /api
# 默认驼峰转成下划线  设为false取消转
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 开启MyBatis-plus的日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置@TableLogic)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
