spring:
  application:
    name: user-center
  datasource:
    url: 'jdbc:mysql://43.137.34.178:3306/db'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Wang158658Wang
  session:
    timeout: 86400
server:
  address: 0.0.0.0