spring:
  application:
    name: yupao-backend
  datasource:
    url: jdbc:mysql://localhost:3306/lkc
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lkc
  session:
    timeout: 86400
server:
  address: 0.0.0.0